device=imx6ull-pro
interval_ms=1000
temperature_path=/tmp/imx6ull_temperature
humidity_path=/tmp/imx6ull_humidity
key_path=/tmp/imx6ull_key_state
led_path=/tmp/imx6ull_led_state
log_path=../logs/sensor_collector.log

